# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'Pr0gramm' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'ScrollingContentViewController'
  pod 'ImageScrollView'
  pod 'Static', git: 'https://github.com/venmo/Static'
  
end
